-- ============================================================================
-- UPDATE BIZPULSE ADMIN PASSWORD
-- Run this in Supabase SQL Editor
-- ============================================================================

-- New Password: BizPulse@2024!
-- Hash: (will be generated by Python hash_password function)

-- First, check if bizpulse admin exists
SELECT 'Checking BizPulse admin account...' AS status;
SELECT id, email, business_name FROM users WHERE email = 'bizpulse.erp@gmail.com';

-- Update password (you need to run Python script to get the hash)
-- Python: from modules.shared.database import hash_password; print(hash_password('BizPulse@2024!'))
-- Then update with that hash

-- For now, this is a placeholder
-- UPDATE users 
-- SET password_hash = 'YOUR_GENERATED_HASH_HERE'
-- WHERE email = 'bizpulse.erp@gmail.com';

SELECT '⚠️  Run Python script to generate hash first!' AS message;
SELECT '   from modules.shared.database import hash_password' AS step1;
SELECT '   print(hash_password("BizPulse@2024!"))' AS step2;
SELECT '   Then update the SQL above with the hash' AS step3;
